[package]
name = "x_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.15", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
futures = "0.3"
twitter-v2 = "0.1.8"
dotenv = "0.15.0"
